import Head from "next/head";

import { ChallengeUI } from "../components/DataFetcher";
import { ConnectWallet } from "../components/ConnectWallet";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Challenge 01 - Data fetching</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ConnectWallet />

        <br />

        <ChallengeUI />
      </main>
    </div>
  );
}
